### ISSUE TITLE
TODO: File

### ISSUE THREAD

**Issue by olyckne** [olyckne/tvshow_parser#2]
- [x] copy file to temp folder
- [x] Remove temp folder
- [x] check if file is video
- [x] extract archive (rar, zip, tgz?)
